# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'gv24App' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for gv24App
  pod 'IoniconsSwift'
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'FacebookShare'
  pod 'Google/SignIn'
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'Firebase/Auth'
    
  pod 'Whisper', :git => 'https://github.com/peihsendoyle/Whisper.git'
  pod 'KMPlaceholderTextView'
  pod 'IQKeyboardManagerSwift'
  pod 'AFNetworking', '~> 2.0’
  pod 'GoogleMobileVision/FaceDetector'
  pod 'GTProgressBar'
end
